### ISSUE TITLE
js-joda Instant doesn't extend protocol cljs.core/Inst

### ISSUE THREAD

**Issue by 2food** [henryw374/cljc.java-time#29]
Was gonna report this at tick, but I think it belongs here instead?

`clojure.core/inst?` is implemented with a protocol `Inst` in both clj and cljs. A `java.time.Instant` implements this protocol in clj, but in cljs it does not. 

Code in clojure.core extending Inst protocol:
```clojure 
(extend-protocol clojure.core/Inst
  java.time.Instant
  (inst-ms* [inst] (.toEpochMilli ^java.time.Instant inst)))
```

This means that
In clojure we have:
```clojure
(inst? (cljc.java-time.instant/now)) ;;=> true
```

but in clojurescript:
```clojure
(inst? (cljc.java-time.instant/now)) ;;=> false
```

I think the cljs implementation should match the clj one, and the js-joda `Instant` in cljs should be extended to implement the `cljs.core/Inst` protocol.

**Comment by henryw374** [comment]
interesting one. 

a quick scan through libs used by some of the apps I manage show a couple of libs making assumption inst? is a js Date - deepdiff2 and spec toos. also with spec, generating an inst? creates platform date. guess same for clojure. maybe it can be overriden? so... wondering if this change will cause some confusion. 

i have avoided inst bc just being the one method it has never done enough to be useful to me. it could generate stuff that is serialized to edn, ie #inst, but thats about it. 

since it is easy to add this in user space, if you find it useful, maybe that's the way to go?

**Comment by 2food** [comment]
Yeah maybe. Especially since people may rely on the existing implementation being only valid for js Date as you mention. 
It just rubs me the wrong way whenever clj and cljs code behaves diffferently. That feels like a bug to me.

**Comment by henryw374** [comment]
ok. so yeah, libs making the assumption that something satisfying `inst?` is a js/Date is wrong. 

were it not for those I think it would be a reasonable change to make.
 
I'll close this for now
